/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gzchocolateria;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author jesuz
 */
public class Cproducto extends javax.swing.JFrame {

    /**
     * Creates new form MenuP
     */
    public Cproducto() {
        initComponents();
        btnGuardar.addActionListener(evt -> guardarP());
    }
    private void guardarP(){
        String Id_producto =txtIdP.getText();
        String nombre_producto =txtNombreP.getText();
        String cantidad  =txtCantidadP.getText();
        String precio =txtPrecioP.getText();
        String descripcion =txtDescripcion.getText();
     
        if (nombre_producto.isEmpty() || cantidad.isEmpty() || precio.isEmpty() || descripcion.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos obligatorios.");
        return;
    }
        try (Connection conn = dbConnection.getConnection()) {
            String sql = "INSERT INTO inventario (Id_producto, nombre_producto, cantidad, precio, Descripcion) "
               + "VALUES (?, ?, ?, ?, ?)";

        try (PreparedStatement as = conn.prepareStatement(sql)) {
        as.setString(1, Id_producto);
        as.setString(2, nombre_producto);
        as.setString(3, cantidad);
        as.setString(4, precio);
        as.setString(5, descripcion); 
          int rowsAffected = as.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Producto registrado exitosamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar producto.");
        }
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Error de conexión a la base de datos: " + e.getMessage());
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblNombreP = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblDescripcionP = new javax.swing.JLabel();
        lblPrecioU1 = new javax.swing.JLabel();
        lblIdP = new javax.swing.JLabel();
        txtCantidadP = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        txtPrecioP = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtNombreP = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        txtIdP = new javax.swing.JTextField();
        btnMenuE1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombreP.setText("Nombre");
        jPanel2.add(lblNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 60, -1));

        lblCantidad.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCantidad.setText("Cantidad");
        jPanel2.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lblDescripcionP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDescripcionP.setText("Descripcion");
        jPanel2.add(lblDescripcionP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        lblPrecioU1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrecioU1.setText("Precio");
        jPanel2.add(lblPrecioU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lblIdP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIdP.setText("id_Producto");
        jPanel2.add(lblIdP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 240));
        jPanel1.add(txtCantidadP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 270, -1));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Creacion de producto");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));
        jPanel1.add(txtPrecioP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 270, -1));

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 270, 20));
        jPanel1.add(txtNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 270, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));
        jPanel1.add(txtIdP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 270, -1));

        btnMenuE1.setText("Menu encargado");
        btnMenuE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuE1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenuE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        Inventario inventario = new Inventario();
        inventario.setVisible(true); 
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnMenuE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuE1ActionPerformed
        // TODO add your handling code here:
         dispose();
         MenuEncargado menuEncargado = new MenuEncargado();
         menuEncargado.setVisible(true); 
         menuEncargado.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnMenuE1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cproducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cproducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMenuE1;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblDescripcionP;
    private javax.swing.JLabel lblIdP;
    private javax.swing.JLabel lblNombreP;
    private javax.swing.JLabel lblPrecioU1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCantidadP;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdP;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtPrecioP;
    // End of variables declaration//GEN-END:variables
}
