/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gzchocolateria;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author jesuz
 */
public class CTrabajador extends javax.swing.JFrame {

    /**
     * Creates new form CTrabajador
     */
    public CTrabajador() {
        initComponents();
        btnGuardar.addActionListener(evt -> guardarDatos());
    }


private void guardarDatos() {
    String Id_trabajador=txtIdT.getText();
    String nombre = txtNombreT.getText();
    String apellido = txtApellidoT.getText();
    String telefono = txtTelefono.getText();
    String correo = txtCorreoT.getText();
    java.util.Date fechaNa = txtFecha.getDate(); // Asegúrate de que FN sea un componente que devuelva un objeto java.util.Date
    String contrasena = new String(txtContrasenaT.getPassword()); // Usamos getPassword para recuperar el valor de la contraseña de un JPasswordField
    String direccion=txtDireccion.getText();

    // Validaciones
    if (nombre.isEmpty() || apellido.isEmpty() || telefono.isEmpty() || correo.isEmpty() || contrasena.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos obligatorios.");
        return;
    }

    if (fechaNa == null) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una fecha válida.");
        return;
    }

    // Convertir la fecha de nacimiento a formato SQL
    java.sql.Date sqlDate = new java.sql.Date(fechaNa.getTime()); // Asegúrate de que fechaNa no sea null

    // Guardar los datos en la base de datos
try (Connection conn = dbConnection.getConnection()) {
    String sql = "INSERT INTO datos_trabajador (Id_trabajador, Nombre, Apellido, Correo, Contrasena, Fecha_Nacimiento, Telefono,Genero,Direccion) "
               + "VALUES (?, ?, ?, ?, ?, ?, ?, ?,?)";
    try (PreparedStatement ps = conn.prepareStatement(sql)) {
        ps.setString(1, Id_trabajador);
        ps.setString(2, nombre);
        ps.setString(3, apellido);
        ps.setString(4, correo);
        ps.setString(5, contrasena);
        ps.setDate(6, sqlDate);
        ps.setString(7, telefono);
        ps.setString(8, cmbGenero.getSelectedItem().toString());
        ps.setString(9, direccion);
       

            int rowsAffected = ps.executeUpdate();
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Trabajador registrado exitosamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar trabajador.");
        }
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "Error de conexión a la base de datos: " + e.getMessage());
}
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblNombreT = new javax.swing.JLabel();
        lblApellidoT = new javax.swing.JLabel();
        lblSueldo = new javax.swing.JLabel();
        lblidTrabajador = new javax.swing.JLabel();
        lblSueldo1 = new javax.swing.JLabel();
        lblSueldo2 = new javax.swing.JLabel();
        lblSueldo3 = new javax.swing.JLabel();
        lblSueldo4 = new javax.swing.JLabel();
        lblSueldo5 = new javax.swing.JLabel();
        txtApellidoT = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtNombreT = new javax.swing.JTextField();
        btnMenu = new javax.swing.JButton();
        txtIdT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        cmbGenero = new javax.swing.JComboBox<>();
        txtCorreoT = new javax.swing.JTextField();
        txtContrasenaT = new javax.swing.JPasswordField();
        txtTelefono = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNombreT.setText("Nombre");
        jPanel2.add(lblNombreT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 60, -1));

        lblApellidoT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblApellidoT.setText("Apellido");
        jPanel2.add(lblApellidoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        lblSueldo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSueldo.setText("Telefono");
        jPanel2.add(lblSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 120, -1));

        lblidTrabajador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblidTrabajador.setText("Id_trabajador");
        jPanel2.add(lblidTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lblSueldo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSueldo1.setText("Direccion");
        jPanel2.add(lblSueldo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        lblSueldo2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSueldo2.setText("Contraseña");
        jPanel2.add(lblSueldo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        lblSueldo3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSueldo3.setText("Correo");
        jPanel2.add(lblSueldo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lblSueldo4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSueldo4.setText("Fecha de nacimiento");
        jPanel2.add(lblSueldo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, -1));

        lblSueldo5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSueldo5.setText("Genero");
        jPanel2.add(lblSueldo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 380));

        txtApellidoT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoTActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellidoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 270, -1));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Creacion de trabajador");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 260, -1));
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 270, 20));
        jPanel1.add(txtNombreT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 270, -1));

        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 323, -1, 20));

        txtIdT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdTActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 80, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Descargas\\bordeNet.jpg")); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 520, 10));
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 200, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Descargas\\bordeNet.jpg")); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 520, 10));

        cmbGenero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        jPanel1.add(cmbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));
        jPanel1.add(txtCorreoT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 270, 20));
        jPanel1.add(txtContrasenaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 260, -1));
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 270, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoTActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        MenuGeneral MenuG=new MenuGeneral();
        MenuG.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuActionPerformed

    private void txtIdTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTrabajador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CTrabajador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JComboBox<String> cmbGenero;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblApellidoT;
    private javax.swing.JLabel lblNombreT;
    private javax.swing.JLabel lblSueldo;
    private javax.swing.JLabel lblSueldo1;
    private javax.swing.JLabel lblSueldo2;
    private javax.swing.JLabel lblSueldo3;
    private javax.swing.JLabel lblSueldo4;
    private javax.swing.JLabel lblSueldo5;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblidTrabajador;
    private javax.swing.JTextField txtApellidoT;
    private javax.swing.JPasswordField txtContrasenaT;
    private javax.swing.JTextField txtCorreoT;
    private javax.swing.JTextField txtDireccion;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtIdT;
    private javax.swing.JTextField txtNombreT;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
