/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gzchocolateria;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author jesuz
 */
public class Horario extends javax.swing.JFrame {

    /**
     * Creates new form Horario
     */
    public Horario() {
        initComponents();
        cargarTrabajadores();
        cargarHorarios();
    }
    
    private void cargarTrabajadores() {
    try (Connection conn = dbConnection.getConnection();
         PreparedStatement stmt = conn.prepareStatement("SELECT nombre FROM datos_trabajador");
         ResultSet rs = stmt.executeQuery()) {

        cmbTrabajador.removeAllItems(); // Limpiar ComboBox
        while (rs.next()) {
            cmbTrabajador.addItem(rs.getString("nombre"));
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar trabajadores: " + e.getMessage());
    }
}
    
    private void cargarHorarios() {
        // Consulta SQL
            String query = "SELECT horario.Id_horario, horario.Id_trabajador, datos_trabajador.Nombre AS Nombre_Trabajador, " +
                           "horario.hora_entrada, horario.hora_salida, horario.Fecha " +
                           "FROM horario " +
                           "INNER JOIN datos_trabajador ON horario.Id_trabajador = datos_trabajador.Id_trabajador";

            // Ejecutar consulta
            
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("Id_trabajador");
    modelo.addColumn("Nombre_Trabajador");
    modelo.addColumn("Fecha");
    modelo.addColumn("Hora de Entrada");
    modelo.addColumn("Hora de Salida");

    try (Connection conn = dbConnection.getConnection();
         PreparedStatement stmt = conn.prepareStatement(query);
         ResultSet rs = stmt.executeQuery()) {

        while (rs.next()) {
            Object[] fila = {
                
                rs.getString("Id_trabajador"),
                rs.getString("Nombre_Trabajador"),
                rs.getDate("fecha"),
                rs.getString("hora_entrada"),
                rs.getString("hora_salida")
            };
            modelo.addRow(fila);
        }
        TablaHorario.setModel(modelo);

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar horarios: " + e.getMessage());
    }
}
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbTrabajador = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaHorario = new javax.swing.JTable();
        btnAsignarH = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtHoraS = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtHoraE = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        HorarioF = new com.toedter.calendar.JDateChooser();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Chocolateria");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("\"La Guelaguetza\"");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(871, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        cmbTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTrabajadorActionPerformed(evt);
            }
        });
        jPanel2.add(cmbTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 90, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Trabajador");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Detalles de horario");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 14));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Horario de la Semana");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, 14));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Dia");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 30, 14));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 10, 330));

        TablaHorario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Dia", "Id_trabajador", "Nombre_Trabajador", "Entrada", "Salida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaHorario);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 580, 180));

        btnAsignarH.setText("Crear");
        btnAsignarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarHActionPerformed(evt);
            }
        });
        jPanel2.add(btnAsignarH, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Horas");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 50, 20));
        jPanel2.add(txtHoraS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 80, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Hora de entrada");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 20));
        jPanel2.add(txtHoraE, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Hora de salida");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 120, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Horas");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 50, 20));

        jButton1.setText("Regresar");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, -1));
        jPanel2.add(HorarioF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 100, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarHActionPerformed
        String trabajadorNombre = cmbTrabajador.getSelectedItem().toString();
    java.util.Date fecha = HorarioF.getDate();
    String horaEntrada = txtHoraE.getText();
    String horaSalida = txtHoraS.getText();

    if (fecha == null || horaEntrada.isEmpty() || horaSalida.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos.");
        return;
    }

    try (Connection conn = dbConnection.getConnection()) {
        // Obtener el Id_trabajador usando el nombre seleccionado
        String idTrabajador;
            idTrabajador = "";
        try (PreparedStatement getIdStmt = conn.prepareStatement(
                "SELECT Id_trabajador FROM datos_trabajador WHERE nombre = ?")) {
            getIdStmt.setString(1, trabajadorNombre);
            ResultSet rs = getIdStmt.executeQuery();
            if (rs.next()) {
                idTrabajador = rs.getString("Id_trabajador");
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró el trabajador seleccionado.");
                return;
            }
        }

        // Insertar el horario
        java.sql.Date sqlFecha = new java.sql.Date(fecha.getTime());
        try (PreparedStatement insertStmt = conn.prepareStatement(
                "INSERT INTO Horario (Id_trabajador, fecha, hora_entrada, hora_salida) VALUES (?, ?, ?, ?)")) {
            insertStmt.setString(1, idTrabajador);
            insertStmt.setDate(2, sqlFecha);
            insertStmt.setString(3, horaEntrada);
            insertStmt.setString(4, horaSalida);
            insertStmt.executeUpdate();
        }

        JOptionPane.showMessageDialog(this, "Horario asignado correctamente.");
        limpiarCampos();
        cargarHorarios(); // Refrescar la tabla
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al asignar horario: " + e.getMessage());
    }
}

private void limpiarCampos() {
    HorarioF.setDate(null);
    txtHoraE.setText("");
    txtHoraS.setText("");

    }//GEN-LAST:event_btnAsignarHActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cmbTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTrabajadorActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Horario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser HorarioF;
    private javax.swing.JTable TablaHorario;
    private javax.swing.JButton btnAsignarH;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbTrabajador;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtHoraE;
    private javax.swing.JTextField txtHoraS;
    // End of variables declaration//GEN-END:variables
}
