/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gzchocolateria;

/**
 *
 * @author jesuz
 */
public class MenuEncargado extends javax.swing.JFrame {

    /**
     * Creates new form MenuEncargado
     */
    public MenuEncargado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblC3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblC = new javax.swing.JLabel();
        btnCProducto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnVentas = new javax.swing.JButton();
        btnAdTrabajador = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        lblC1 = new javax.swing.JLabel();
        lblC2 = new javax.swing.JLabel();
        lblC4 = new javax.swing.JLabel();
        lblC5 = new javax.swing.JLabel();

        lblC3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblC3.setText("Trabajadores");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("\"La Guelaguetza\"");

        lblC.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblC.setText("Chocolateria");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4))
                    .addComponent(lblC, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblC)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 80));

        btnCProducto.setBackground(new java.awt.Color(102, 102, 255));
        btnCProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCProducto.setIcon(new javax.swing.ImageIcon("D:\\Descargas\\iconoInventario.png")); // NOI18N
        btnCProducto.setToolTipText("");
        btnCProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), new java.awt.Color(102, 0, 204)));
        btnCProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 180, 150));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Menu de encargado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 170, -1));

        btnVentas.setBackground(new java.awt.Color(255, 51, 51));
        btnVentas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVentas.setIcon(new javax.swing.ImageIcon("D:\\Descargas\\iconoVentass.png")); // NOI18N
        btnVentas.setToolTipText("");
        btnVentas.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), new java.awt.Color(102, 0, 204)));
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        jPanel1.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 180, 150));

        btnAdTrabajador.setBackground(new java.awt.Color(102, 204, 255));
        btnAdTrabajador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdTrabajador.setIcon(new javax.swing.ImageIcon("D:\\Descargas\\iconoTrabajadores.png")); // NOI18N
        btnAdTrabajador.setToolTipText("");
        btnAdTrabajador.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), new java.awt.Color(102, 0, 204)));
        btnAdTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdTrabajadorActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 180, 150));

        btnProveedores.setBackground(new java.awt.Color(153, 255, 255));
        btnProveedores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProveedores.setIcon(new javax.swing.ImageIcon("D:\\Descargas\\iconoProveedores.png")); // NOI18N
        btnProveedores.setToolTipText("");
        btnProveedores.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), new java.awt.Color(102, 0, 204)));
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        jPanel1.add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, 150));

        lblC1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblC1.setText("Trabajadores");
        jPanel1.add(lblC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 110, -1));

        lblC2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblC2.setText("Inventario");
        jPanel1.add(lblC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 120, -1));

        lblC4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblC4.setText("Ventas");
        jPanel1.add(lblC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 60, -1));

        lblC5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblC5.setText("Proveedores");
        jPanel1.add(lblC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCProductoActionPerformed
        // TODO add your handling code here:
        Inventario inventariot=new Inventario();
        inventariot.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCProductoActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
        VentaE ventaE=new VentaE();
        ventaE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnAdTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdTrabajadorActionPerformed
        // TODO add your handling code here:
        AdTrabajador adtrabajador=new AdTrabajador();
        adtrabajador.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnAdTrabajadorActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        // TODO add your handling code here:
        VerProveedor proveedor=new VerProveedor();
        proveedor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProveedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEncargado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEncargado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdTrabajador;
    private javax.swing.JButton btnCProducto;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblC;
    private javax.swing.JLabel lblC1;
    private javax.swing.JLabel lblC2;
    private javax.swing.JLabel lblC3;
    private javax.swing.JLabel lblC4;
    private javax.swing.JLabel lblC5;
    // End of variables declaration//GEN-END:variables
}
